# Overnight autonomous orchestrator: downloads -> P1 desk -> morning report
$ErrorActionPreference = "Continue"
$Root = "D:\DNK - 2\DNA_TE_3DGenome_Context"
$Data = "D:\DNK - 2\data\HUDEP2_GSE160422"
$Out = Join-Path $Root "09_outputs\prospective"
$Log = Join-Path $Out "overnight_orchestrator_log.txt"
$PyP1 = Join-Path $Root "pilot_scaffold\scripts\run_p1_3primeHS1_desk.py"
$Report = Join-Path $Out "MORNING_STATUS_2026-07-15.md"
$Java = "D:\DNK - 2\tools\jdk-17\bin\java.exe"
$Jar = Join-Path $Root "pilot_scaffold\tools\juicer_tools.jar"

New-Item -ItemType Directory -Force $Data, $Out | Out-Null
function Log($m) {
  $line = "[{0}] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $m
  Add-Content -Path $Log -Value $line -Encoding UTF8
  Write-Host $line
}

function FileBytes($path) {
  if (Test-Path $path) { (Get-Item $path).Length } else { 0 }
}

function DownloadOne($name, $url, $minBytes) {
  $path = Join-Path $Data $name
  $attempt = 0
  while ($attempt -lt 120) {
    $attempt++
    $size = FileBytes $path
    Log ("DOWNLOAD {0} attempt={1} MB={2:N1} target>={3:N0}" -f $name, $attempt, ($size/1MB), ($minBytes/1MB))
    if ($size -ge $minBytes) {
      Log ("COMPLETE {0} bytes={1}" -f $name, $size)
      return $true
    }
    & curl.exe -L -C - --retry 15 --retry-delay 10 --connect-timeout 60 --speed-time 120 --speed-limit 500 -o $path $url
    $ec = $LASTEXITCODE
    $size2 = FileBytes $path
    Log ("curl_exit={0} MB={1:N1}" -f $ec, ($size2/1MB))
    if ($ec -eq 0 -and $size2 -ge $minBytes) {
      Log ("SUCCESS {0}" -f $name)
      return $true
    }
    Start-Sleep -Seconds 20
  }
  Log ("FAILED {0}" -f $name)
  return $false
}

function Sha256($path) {
  if (-not (Test-Path $path)) { return $null }
  return (Get-FileHash -Path $path -Algorithm SHA256).Hash
}

function RunP1 {
  Log "RUN_P1_DESK"
  try {
    $out = & python $PyP1 2>&1 | Out-String
    Add-Content -Path $Log -Value $out -Encoding UTF8
    Log "P1_DESK_DONE"
  } catch {
    Log ("P1_DESK_ERROR {0}" -f $_.Exception.Message)
  }
}

Log "===== ORCHESTRATOR START ====="
Log ("java_exists={0}" -f (Test-Path $Java))

$queue = @(
  @{n="GSM4873116_WT-HUDEP2-captureHiC_allValidPairs.hic"; u="https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4873nnn/GSM4873116/suppl/GSM4873116_WT-HUDEP2-captureHiC_allValidPairs.hic"; min=2300000000},
  @{n="GSM4873117_B6-HUDEP2-captureHiC_allValidPairs.hic"; u="https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4873nnn/GSM4873117/suppl/GSM4873117_B6-HUDEP2-captureHiC_allValidPairs.hic"; min=2300000000},
  @{n="GSM4873118_A2-HUDEP2-captureHiC_allValidPairs.hic"; u="https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4873nnn/GSM4873118/suppl/GSM4873118_A2-HUDEP2-captureHiC_allValidPairs.hic"; min=2100000000},
  @{n="GSM4873114_B6-HUDEP2-HiC_allValidPairs.hic"; u="https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4873nnn/GSM4873114/suppl/GSM4873114_B6-HUDEP2-HiC_allValidPairs.hic"; min=7000000000},
  @{n="GSM4873115_A2-HUDEP2-HiC_allValidPairs.hic"; u="https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4873nnn/GSM4873115/suppl/GSM4873115_A2-HUDEP2-HiC_allValidPairs.hic"; min=6700000000}
)

$results = @{}
foreach ($q in $queue) {
  $ok = DownloadOne $q.n $q.u $q.min
  $results[$q.n] = @{ ok = $ok; bytes = (FileBytes (Join-Path $Data $q.n)) }
  if ($q.n -like "*capture*" -or $q.n -like "*3114*" -or $q.n -like "*3115*") {
    RunP1
  }
}

Log "CHECKSUMS"
$csv = Join-Path $Data "checksums_sha256_all.csv"
"Algorithm,Hash,Path,Bytes" | Set-Content $csv -Encoding UTF8
Get-ChildItem (Join-Path $Data "*.hic") | ForEach-Object {
  Log ("hashing {0} ..." -f $_.Name)
  $h = Sha256 $_.FullName
  '"{0}","{1}","{2}",{3}' -f "SHA256", $h, $_.FullName, $_.Length | Add-Content $csv -Encoding UTF8
  Log ("SHA256 {0} {1}" -f $_.Name, $h)
}

RunP1

# Read P1 verdict if present
$p1json = Join-Path $Out "P1_3primeHS1_metrics.json"
$verdict = "UNKNOWN"
if (Test-Path $p1json) {
  try {
    $j = Get-Content $p1json -Raw | ConvertFrom-Json
    $verdict = $j.verdict
  } catch { $verdict = "PARSE_ERROR" }
}

$g4a = "PASS_DESK"
$archFreeze = if ($verdict -match "PASS") { "PROVISIONAL_OPEN_LANGUAGE_ONLY" } else { "NO-GO" }

$md = @"
# Morning status — 2026-07-15

**Generated by:** overnight orchestrator  
**Log:** ``overnight_orchestrator_log.txt``

## Machine status

``````text
G4a WT Contact(E,P):     $g4a (GSM4873113)
P1-system 3'HS1 desk:    $verdict
architecture freeze:     $archFreeze
G4b allele contact:      NOT TESTED
wet-lab GO:              NO-GO
activity Branch B:       CONDITIONAL GO
ARCHCODE:                EXPLORATORY only
``````

## Files

| File | Bytes | OK |
|------|------:|----|
$(($queue | ForEach-Object { $b = FileBytes (Join-Path $Data $_.n); $ok = if ($b -ge $_.min) { "yes" } else { "partial" }; "| $($_.n) | $b | $ok |" }) -join "`n")
| GSM4873113_WT-HUDEP2-HiC_allValidPairs.hic | $(FileBytes (Join-Path $Data 'GSM4873113_WT-HUDEP2-HiC_allValidPairs.hic')) | yes |

Checksums: ``$Data\checksums_sha256_all.csv``

## Next for human (morning)

1. Read ``P1_3primeHS1_desk_pass_v1.md`` and ``G4a_gsm4873113_desk_pass_v1.md``
2. If P1 PASS → draft G4b Capture-C/MCC protocol for locked E/P (still no wet GO)
3. If P1 pending/fail → continue Branch B activity; keep architecture claim frozen out
4. PE pegRNA desk for C1 still open desk work

## Allowed claim language

- OK: sequence/activity candidate; HUDEP-2 E–P contact desk-detected at locked anchors
- OK only if P1 PASS: provisional architecture panel design (assay-chain grounded)
- FORBIDDEN until G4b: "C1 disrupts E–P loop in HUDEP-2"
"@

Set-Content -Path $Report -Value $md -Encoding UTF8
Log ("WROTE_REPORT {0}" -f $Report)

# Soft-update PAUSE_PIN status block
$pin = Join-Path $Out "PAUSE_PIN_2026-07-14.md"
if (Test-Path $pin) {
  Log "PAUSE_PIN present (manual merge if needed)"
}

Log "===== ORCHESTRATOR END ====="
